// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { publicEnv } from '@/config/public-env';

const SUPABASE_URL =
  publicEnv("VITE_SUPABASE_URL") ||
  (publicEnv("VITE_SUPABASE_PROJECT_ID")
    ? `https://${publicEnv("VITE_SUPABASE_PROJECT_ID")}.supabase.co`
    : undefined);
const SUPABASE_PUBLISHABLE_KEY =
  publicEnv("VITE_SUPABASE_PUBLISHABLE_KEY") ||
  publicEnv("VITE_SUPABASE_ANON_KEY");

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Fail fast with a clear message instead of the cryptic "supabaseUrl is required".
  throw new Error(
    "[Motivai] إعدادات Supabase مفقودة: عرّف VITE_SUPABASE_URL و VITE_SUPABASE_PUBLISHABLE_KEY في ملف .env قبل البناء، أو في متغيرات البيئة (Environment Variables) على منصة النشر."
  );
}


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
